const quotes=[
	"/me Smart ahhh wire",
	"/me uh balls FUNNY",
	"/me my balls itch",
	"/me FlowerCatJAM FlowerCatJAM FlowerCatJAM FlowerCatJAM FlowerCatJAM FlowerCatJAM FlowerCatJAM FlowerCatJAM FlowerCatJAM FlowerCatJAM FlowerCatJAM FlowerCatJAM FlowerCatJAM FlowerCatJAM FlowerCatJAM FlowerCatJAM FlowerCatJAM FlowerCatJAM FlowerCatJAM FlowerCatJAM FlowerCatJAM FlowerCatJAM FlowerCatJAM FlowerCatJAM FlowerCatJAM FlowerCatJAM FlowerCatJAM FlowerCatJAM FlowerCatJAM FlowerCatJAM FlowerCatJAM FlowerCatJAM FlowerCatJAM FlowerCatJAM FlowerCatJAM FlowerCatJAM FlowerCatJAM FlowerCatJAM",
	"/me if you look like or are a lovander DM ME IMMEDIATELYYYYYYY",
	"/me https://www.youtube.com/watch?v=f920UH-kk2g",
	"/me crafting_table_ :tf: 🤜 🔔",
	"/me if you see this post Joel",
	"/me I couldn't even Jingle to this😂🎄 I Caroled IMMEDIATELY !! 😂😂 Gift Wrap Isle MY PRESENTS! 🎁😂🥰",
	"/me chatis is kind of based BRUHMM",
	"/me 🗣️",
	"/me 🚨 REMINDER CHAT YOU HAVE A 1/7 CHANCE TO GET FREE VIP IF YOU TYPE !dayoff YESSIR",
	"/me dont forget to download 7tv FeelsOkayMan 👉 https://7tv.app/",
	"/me Joe many liberals does it take to change a log by bulb????? None , their to busy ???? Their Gender 😂 😂 😂 😂 😂 😂 ",
	"/me shameless self promo https://neomoth.dev shug",
	"/me `user` catKISS",
	"/me The thing about me? It's that i'm a Weest girlie fruitySpin Catch me pogging at the twitch notification alerting me to his streams, and kicking my legs in the air while watching him SWOONER It's not weird ReallyMad I'm proud of my Weest appreciation :3 He is my little guy in my little phone yo God, i wish he was real Sadge What i wouldn't do to have Weest actually exist Happs He's my little meow meow catboy babey WOWZERS",
	"/me im fucking balling",
	"/me boner?? i hardly even know 'er! 😂😂😂😂😂😂😂😂",
	"/me The thing about me? It's that I'm a Weest enjoyer. Hmm Catch me acknowledging the Twitch notification alerting me to his streams, and SOMEWHAT paying attention to what he's saying/doing. shug It's not weird. BRUHMM I'm content with my Weest acquaintanceship. buh He is a random person on my computer monitor. shrug I don't really care if he's real or not. okay I think I would be kinda intrigued if he were real and met him in person. OHHH",
	"/me o7",
	"/me WHY DONT YOU PUT THAT FUCKIN PHOOOOOOONE DOOOOOOOWN Chica",
	"/me The thing about me? It's that i'm a Weest HATER ReallyMad Catch me ENRAGING at the twitch notification alerting me to his streams, and hitting my computer while watching him SCHIZO It's not weird Insane I'm proud of my Weest HATE pepeMeltdown He is the little stupid in my big phone anguish God, i wish he wasNT real Madge  What i wouldn't do to have Weest actually NOT exist NOOOYOUCANT",
	"/me The thing about me? It's that I'm a Weest VILIFIER UltraMad Catch me SEETHING at the tweet of one of my friends who watches him‼🤮And BLOCKING him on every social media platform I have an account on. WOWZERS CANCELLED It's not weird. OKAY I'm Proud of my Weest HATRED‼ HISNAMEIS He is the STUPID MOTHERFUCKER that unfortunately shares the SAME PLANET of residence as me‼ God, I wish he was DEPLATFORMED‼👎 He is the INSUFFERABLE content creator at the back of my mind CONSTANTLY‼ Parasocial",
	"/me ome47 FUCK YOU DAYTONA",
	"/me in the stripped club. straight up \"jorking it\". and by \"it\", haha, well. let's just say. My peanits .",
	"/me I FUCKING LOVE MOTHS MUGA",
	"/me https://www.youtube.com/watch?v=wewY9GT-Qjk",
	"/me Rexo MyBeloved",
	"/me can i get a one dance quota",
	"/me rora WIDEALERT",
	"/me `name` gift 50 subs rn or !dayoff NOW",
	"/me WOWZERS",
	"/me @Weest if this one gets rolled you gotta do streetbeefs i dont make the rules",
	"?cookie",
	"!gay",
	"/me flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea flea",
	"/me if you read this ur gay BLEHHHH GayTime",
	"/me ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ imGlitch Chat is now in buh only mode! imGlitch ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬",
	"$fish",
	"/me peanits Happs",
	"/me Sooo my pee is motherhecking purple now. Yep. Idk how this even happened but well- Leeeets just say my pee is totally friggin PURPLE now. Weirdly, it's only ever in one toilet too: I think this particular terlet of mine detests me? Anyways, it doesnt even smell that bad either which is the creepiest part. Any ideas? Reddit, assemble!",
	"/me omeScrajj what? are you expecting me to say something funny? im kind of running out of material here. its not that easy posting a funny message or link every time you need a little bit of stimulation. you should be more considerate of my feelings next time.",
	"/me PrideHardo GAY MODE PrideHardo GAY MODE PrideHardo GAY MODE PrideHardo GAY MODE PrideHardo GAY MODE PrideHardo GAY MODE",
	"/me WOWZERS The way weest stands in this emote is literally the most thug-gangster ass-shit like holy hell it's so badass",
	"/me I'm over here stroking my dick I got lotion on my dick right now I'm just stroking my shit I'm horny as fuck man I'm a freak man like",
	"/me 1/300 chance to get this message SUBLIME",
	"/me Thank god it don't got red 21 in it. 21. What's 9 + 10? 21. Thank god it don't got that in it. What's 9 + 10? 21. Thank god it don't got that in it, man. 21- You stupid. No I'm not. What's 9 + 10? 21. Thank god it don't got red 21. You stupid. No I'm not. What's 9 + 10? 21. Man, you stupid. Tha- tha thank god it don't got that in it. Thank god It got red 21. ",
	"/me nonverbal ALERT soyPoint",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me ",
	// "/me "
]

module.exports ={
	data:{
		name:'randomquote',
		description:'Spit out one of many, MANY random messages.',
		aliases:['rq']
	},
	async run(client, e,args){
		let quote = quotes[Math.floor(Math.random()*quotes.length)];
		quote = quote.replace('`name`', e.senderUsername);
		client.privmsg(e.channelName, quote);
	}
}